-- Auto-generated by scripts/crawl_efi.py
-- EFI team aggregate stats for all 48 WC26 teams
-- Source: https://efidatareference.com

SET NAMES utf8mb4;

-- ── Teams ──────────────────────────────────────────────────────────
-- Colors verified: no two teams in the same match share a color.
-- Legend: red=ENG/ESP/KOR/CAN/MAR  orange=NED/CIV/COL/AUT  yellow=GER/BRA/SWE/ECU/RSA/AUS
--         lime=MEX/KSA/GHA/SEN/NOR/SUI  teal=QAT/ALG/NZL/HAI/CPV  blue=FRA/ARG/JPN/SCO/USA
--         indigo=URU/BIH/COD/BEL/CUR  lavender=CRO/POR/PAN/PAR/TUN  pink=EGY/CZE/IRN/JOR/TUR/IRQ/UZB
INSERT INTO teams (slug, name, short_code, group_letter, color) VALUES
  ('algeria',           'Algeria',                'ALG', NULL, '--c-teal'),
  ('argentina',         'Argentina',              'ARG', NULL, '--c-blue'),
  ('australia',         'Australia',              'AUS', NULL, '--c-yellow'),
  ('austria',           'Austria',                'AUT', NULL, '--c-orange'),
  ('belgium',           'Belgium',                'BEL', NULL, '--c-indigo'),
  ('bosnia-herzegovina','Bosnia and Herzegovina', 'BIH', NULL, '--c-indigo'),
  ('brazil',            'Brazil',                 'BRA', NULL, '--c-yellow'),
  ('cabo-verde',        'Cabo Verde',             'CPV', NULL, '--c-teal'),
  ('canada',            'Canada',                 'CAN', NULL, '--c-red'),
  ('colombia',          'Colombia',               'COL', NULL, '--c-orange'),
  ('congo-dr',          'Congo DR',               'COD', NULL, '--c-indigo'),
  ('cote-divoire',      'Côte d''Ivoire',         'CIV', NULL, '--c-orange'),
  ('croatia',           'Croatia',                'CRO', NULL, '--c-lavender'),
  ('czechia',           'Czechia',                'CZE', NULL, '--c-pink'),
  ('ecuador',           'Ecuador',                'ECU', NULL, '--c-yellow'),
  ('egypt',             'Egypt',                  'EGY', NULL, '--c-pink'),
  ('england',           'England',                'ENG', NULL, '--c-red'),
  ('france',            'France',                 'FRA', NULL, '--c-blue'),
  ('ghana',             'Ghana',                  'GHA', NULL, '--c-lime'),
  ('haiti',             'Haiti',                  'HAI', NULL, '--c-teal'),
  ('ir-iran',           'IR Iran',                'IRN', NULL, '--c-pink'),
  ('iraq',              'Iraq',                   'IRQ', NULL, '--c-pink'),
  ('japan',             'Japan',                  'JPN', NULL, '--c-blue'),
  ('jordan',            'Jordan',                 'JOR', NULL, '--c-pink'),
  ('korea-republic',    'Korea Republic',         'KOR', NULL, '--c-red'),
  ('mexico',            'Mexico',                 'MEX', NULL, '--c-lime'),
  ('morocco',           'Morocco',                'MAR', NULL, '--c-red'),
  ('netherlands',       'Netherlands',            'NED', NULL, '--c-orange'),
  ('new-zealand',       'New Zealand',            'NZL', NULL, '--c-teal'),
  ('norway',            'Norway',                 'NOR', NULL, '--c-lime'),
  ('panama',            'Panama',                 'PAN', NULL, '--c-lavender'),
  ('paraguay',          'Paraguay',               'PAR', NULL, '--c-lavender'),
  ('portugal',          'Portugal',               'POR', NULL, '--c-lavender'),
  ('qatar',             'Qatar',                  'QAT', NULL, '--c-teal'),
  ('saudi-arabia',      'Saudi Arabia',           'KSA', NULL, '--c-lime'),
  ('scotland',          'Scotland',               'SCO', NULL, '--c-blue'),
  ('senegal',           'Senegal',                'SEN', NULL, '--c-lime'),
  ('south-africa',      'South Africa',           'RSA', NULL, '--c-yellow'),
  ('spain',             'Spain',                  'ESP', NULL, '--c-red'),
  ('sweden',            'Sweden',                 'SWE', NULL, '--c-yellow'),
  ('switzerland',       'Switzerland',            'SUI', NULL, '--c-lime'),
  ('tunisia',           'Tunisia',                'TUN', NULL, '--c-lavender'),
  ('turkiye',           'Türkiye',                'TUR', NULL, '--c-pink'),
  ('uruguay',           'Uruguay',                'URU', NULL, '--c-indigo'),
  ('usa',               'USA',                    'USA', NULL, '--c-blue'),
  ('uzbekistan',        'Uzbekistan',             'UZB', NULL, '--c-pink')
ON DUPLICATE KEY UPDATE color=VALUES(color), name=VALUES(name);

-- ── Team aggregate match_stats ────────────────────────────────────
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 50.8, 4.6, 44.6, 0
FROM teams t WHERE t.slug = 'algeria'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 44.6, 4.6, 50.8, 3
FROM teams t WHERE t.slug = 'argentina'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 28.65, 11.9, 59.45, 2
FROM teams t WHERE t.slug = 'australia'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 53.3, 13.7, 33, 3
FROM teams t WHERE t.slug = 'austria'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 45.5, 16.4, 38.1, 1
FROM teams t WHERE t.slug = 'belgium'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 32, 12.7, 55.3, 2
FROM teams t WHERE t.slug = 'bosnia-herzegovina'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 47.85, 7.9, 44.2, 4
FROM teams t WHERE t.slug = 'brazil'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 25.4, 8.9, 65.7, 0
FROM teams t WHERE t.slug = 'cabo-verde'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 59.3, 15.5, 25.2, 7
FROM teams t WHERE t.slug = 'canada'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 56.7, 9.4, 33.9, 3
FROM teams t WHERE t.slug = 'colombia'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 25.3, 5.8, 68.9, 1
FROM teams t WHERE t.slug = 'congo-dr'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 41.9, 8.2, 49.9, 1
FROM teams t WHERE t.slug = 'cote-divoire'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 43.5, 7.5, 49, 2
FROM teams t WHERE t.slug = 'croatia'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 35.3, 6.9, 57.8, 1
FROM teams t WHERE t.slug = 'curacao'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 33.3, 8.7, 58.05, 2
FROM teams t WHERE t.slug = 'czechia'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 49.9, 8.2, 41.9, 0
FROM teams t WHERE t.slug = 'ecuador'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 38.1, 16.4, 45.5, 1
FROM teams t WHERE t.slug = 'egypt'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 49, 7.5, 43.5, 4
FROM teams t WHERE t.slug = 'england'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 49.4, 6.1, 44.5, 3
FROM teams t WHERE t.slug = 'france'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 57.8, 6.9, 35.3, 7
FROM teams t WHERE t.slug = 'germany'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 35.6, 8.9, 55.5, 1
FROM teams t WHERE t.slug = 'ghana'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 47.4, 7.9, 44.75, 0
FROM teams t WHERE t.slug = 'haiti'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 43.3, 11.4, 45.3, 2
FROM teams t WHERE t.slug = 'ir-iran'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 34.7, 8.1, 57.2, 1
FROM teams t WHERE t.slug = 'iraq'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 37.4, 7.7, 54.9, 2
FROM teams t WHERE t.slug = 'japan'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 33, 13.7, 53.3, 1
FROM teams t WHERE t.slug = 'jordan'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', NULL, NULL, NULL, NULL
FROM teams t WHERE t.slug = 'korea-republic'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 48.95, 7.1, 43.95, 3
FROM teams t WHERE t.slug = 'mexico'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 50, 7.1, 42.9, 2
FROM teams t WHERE t.slug = 'morocco'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 54.9, 7.7, 37.4, 2
FROM teams t WHERE t.slug = 'netherlands'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 45.3, 11.4, 43.3, 2
FROM teams t WHERE t.slug = 'new-zealand'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 57.2, 8.1, 34.7, 4
FROM teams t WHERE t.slug = 'norway'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 55.5, 8.9, 35.6, 0
FROM teams t WHERE t.slug = 'panama'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 23.95, 12.4, 63.6, 2
FROM teams t WHERE t.slug = 'paraguay'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 68.9, 5.8, 25.3, 1
FROM teams t WHERE t.slug = 'portugal'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 24.65, 13.1, 62.25, 1
FROM teams t WHERE t.slug = 'qatar'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 27.1, 9.6, 63.3, 1
FROM teams t WHERE t.slug = 'saudi-arabia'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 39.8, 7.0, 53.2, 1
FROM teams t WHERE t.slug = 'scotland'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 44.5, 6.1, 49.4, 1
FROM teams t WHERE t.slug = 'senegal'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 48.2, 7.0, 44.75, 1
FROM teams t WHERE t.slug = 'south-africa'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 65.7, 8.9, 25.4, 0
FROM teams t WHERE t.slug = 'spain'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 47.4, 9.9, 42.7, 5
FROM teams t WHERE t.slug = 'sweden'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 58.25, 10.3, 31.45, 5
FROM teams t WHERE t.slug = 'switzerland'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 42.7, 9.9, 47.4, 1
FROM teams t WHERE t.slug = 'tunisia'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 65.3, 11.6, 23.1, 0
FROM teams t WHERE t.slug = 'turkiye'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 63.3, 9.6, 27.1, 1
FROM teams t WHERE t.slug = 'uruguay'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 57.75, 12.8, 29.5, 6
FROM teams t WHERE t.slug = 'usa'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);
INSERT INTO match_stats (team_id, match_id, scope, possession_team_a, possession_in_contest, possession_team_b, goals_a)
SELECT t.id, NULL, 'team_aggregate', 33.9, 9.4, 56.7, 1
FROM teams t WHERE t.slug = 'uzbekistan'
ON DUPLICATE KEY UPDATE possession_team_a=VALUES(possession_team_a), goals_a=VALUES(goals_a);

