from sqlalchemy import Column, Integer, SmallInteger, Numeric, ForeignKey, Enum, Computed
from app.models.base import Base


class PlayerStat(Base):
    __tablename__ = "player_stats"

    id = Column(Integer, primary_key=True, autoincrement=True)
    player_id = Column(Integer, ForeignKey("players.id"), nullable=False)
    match_id = Column(Integer, ForeignKey("matches.id"), nullable=True)
    scope = Column(Enum("match", "team_aggregate"), nullable=False, default="match")
    match_key = Column(Integer, Computed("IFNULL(match_id,0)"), nullable=False)
    # Match summary (page 2)
    saves = Column(Integer, default=0)
    goals_conceded = Column(Integer, default=0)
    xg_faced = Column(Numeric(5, 2), default=0.00)
    goals = Column(Integer, default=0)
    yellow_cards = Column(Integer, default=0)
    red_cards = Column(Integer, default=0)
    started = Column(SmallInteger, default=1)
    minutes_played = Column(Integer, default=90)
    # In Possession — Distributions (page 42/44)
    passes_attempted = Column(Integer, nullable=True)
    passes_completed = Column(Integer, nullable=True)
    pass_completion_pct = Column(Integer, nullable=True)
    switches_of_play = Column(Integer, nullable=True)
    crosses_attempted = Column(Integer, nullable=True)
    crosses_completed = Column(Integer, nullable=True)
    lb_attempted = Column(Integer, nullable=True)
    lb_completed = Column(Integer, nullable=True)
    ball_progressions = Column(Integer, nullable=True)
    take_ons = Column(Integer, nullable=True)
    step_ins = Column(Integer, nullable=True)
    attempts_at_goal = Column(Integer, nullable=True)
    # In Possession — Offers & Receptions (page 43/45)
    total_offers = Column(Integer, nullable=True)
    offers_received = Column(Integer, nullable=True)
    offers_in_front = Column(Integer, nullable=True)
    offers_in_between = Column(Integer, nullable=True)
    offers_out_to_in = Column(Integer, nullable=True)
    offers_in_to_out = Column(Integer, nullable=True)
    offers_in_behind = Column(Integer, nullable=True)
    offers_no_movement = Column(Integer, nullable=True)
    # Out of Possession (page 47/48)
    tackles_made = Column(Integer, nullable=True)
    tackles_won = Column(Integer, nullable=True)
    blocks = Column(Integer, nullable=True)
    interceptions = Column(Integer, nullable=True)
    pressing_direct = Column(Integer, nullable=True)
    pressing_indirect = Column(Integer, nullable=True)
    duels_won_aerial = Column(Integer, nullable=True)
    duels_won_physical = Column(Integer, nullable=True)
    possession_contests_won = Column(Integer, nullable=True)
    clearances = Column(Integer, nullable=True)
    possession_regains = Column(Integer, nullable=True)
    loose_ball_receptions = Column(Integer, nullable=True)
    pushing_on = Column(Integer, nullable=True)
    pushing_on_into_pressing = Column(Integer, nullable=True)
    possession_interrupted = Column(Integer, nullable=True)
    # Physical Data (page 50/51)
    total_distance_m = Column(Numeric(8, 1), nullable=True)
    dist_zone1_m = Column(Numeric(8, 1), nullable=True)
    dist_zone2_m = Column(Numeric(8, 1), nullable=True)
    dist_zone3_m = Column(Numeric(8, 1), nullable=True)
    dist_zone4_m = Column(Numeric(8, 1), nullable=True)
    dist_zone5_m = Column(Numeric(8, 1), nullable=True)
    high_speed_runs = Column(Integer, nullable=True)
    sprints = Column(Integer, nullable=True)
    top_speed_kmh = Column(Numeric(4, 1), nullable=True)
    # Cross delivery type (pages 18/19)
    crosses_inswing = Column(Integer, nullable=True)
    crosses_outswing = Column(Integer, nullable=True)
    crosses_driven = Column(Integer, nullable=True)
    crosses_lofted = Column(Integer, nullable=True)
    crosses_cutback = Column(Integer, nullable=True)
    crosses_push_cross = Column(Integer, nullable=True)
